### ISSUE TITLE
Reunion Presencial de Team

### ISSUE THREAD

**Issue by Zelechos** [Zelechos/Torneos-de-Tenis-de-Mesa-basado-en-llaves#36]
# **Puntos  a tratar en la reunion presencial :** 
### Se Solicita la presencia sin falta de : @Zelechos  @rodrygo-c-garcia  @Luis99DavidFloresTorres 
-----------------
- [ ] #37
- [ ] Crear todas las Issues del Proyecto en base a todas las Historias de Usuario
- [ ] Vistas del Software
- [x] Diagrama de BD y Tipos de Datos
- [ ] Organizacion de Plantillas y Documentacion del ingeniero pertinentes al software
- [ ] Programar fechas de entrega de Software 

> _Se Exige Puntualidad a las 7:55 am para iniciar 8:00 am  en lo posible traer ideas y cualquier otro material que acelere el proceso de organizacion del proyecto Gracias!!!_

**Comment by rodrygo-c-garcia** [comment]
Ya quedó claro bro @Zelechos ... 7:55am ;)
